# Generated by Django 3.1.4 on 2020-12-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='airport',
            field=models.IntegerField(choices=[(1, 'а/п Борисполь'), (2, 'а/п Шереметьево'), (3, 'а/п Внуково'), (4, 'а/п Домодедово'), (5, 'а/п Остафьево'), (6, 'а/п Жуковский')], default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.IntegerField(choices=[(1, 'Могилёв'), (2, 'Шклов'), (3, 'Бобруйск'), (4, 'Гомель'), (5, 'Орша')], default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
