# Generated by Django 3.1.5 on 2021-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201226_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.IntegerField(choices=[(1, 'Могилёв'), (2, 'Шклов'), (3, 'Бобруйск'), (4, 'Гомель'), (5, 'Орша')], default=1)),
                ('airport', models.IntegerField(choices=[(1, 'а/п Борисполь'), (2, 'а/п Шереметьево'), (3, 'а/п Внуково'), (4, 'а/п Домодедово'), (5, 'а/п Остафьево'), (6, 'а/п Жуковский')], default=1)),
                ('price', models.IntegerField(default=1)),
                ('is_child', models.BooleanField(default=False)),
            ],
        ),
    ]
